### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [KimsCode/colmar_academy#7]
Satisfactory 👍

You're done a great job writing a fully mobile responsive website and should be excited to show off your new skill!

Just for practice you should see if you can make some nice mobile versions of your previous sites. There's no reason why you shouldn't leave this program without a full portfolio mobile responsive websites!

**Comment by KimsCode** [comment]
Thank you, Steve. I found the pro-intensive stressful and have plans to go back and fully immerse myself in what was covered.

**Comment by KimsCode** [comment]
Also, thank you for your tips and pointers. They were very helpful.
